language: node_js
node_js:
  - "6.11.0"
  
addons:
  postgresql: "9.5"
  
services:
  - postgresql

before_script:
  - sudo apt-get install postgresql postgresql-contrib
  - psql -c 'create database travis;' -U postgres

env:
  global:
    - TEST_DATABASE_URL="postgres://postgres@localhost:5432/travis"
    - JWT_SECRET="some-super-secure-secret-i-will-never-use-in-production"
    - PORT="3000"
