language: node_js
node_js:
  - "6.11.0"
  
services:
  - postgresql
addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mkdir config && cp database.travis.yml config/database.yml
  - export TEST_DATABASE_URL="postgres://postgres:test_password@localhost:5432/travis_ci_test"
  - export JWT_SECRET="some-super-secure-secret-i-will-never-use-in-production"
  - export PORT="3000"
